model:
  name: "yolov8n-emo"
  task: "classification"
  input_size: [640,640]  # 输入图像尺寸
  classes: ["anger", "fear", "happy", "neutral", "sad"]
  normalization:
    mean: [0.485, 0.456, 0.406]  # ImageNet均值
    std: [0.229, 0.224, 0.225]    # ImageNet标准差

# 训练参数
training:
  batch_size: 32
  epochs: 100
  optimizer: "AdamW"
  learning_rate: 0.001

# 部署配置
deployment:
  onnx_opset: 12                  # ONNX算子集版本
  tensorrt_precision: "FP16"       # TensorRT计算精度
  max_workspace_size: 2           # GPU工作空间大小(GB)